title: Quest seeker
hero_image: images/banner.png
description: Add NPCs and quests to the world that you created in the World builder project 
version: 4
listed: true
copyedit: true
last_tested: "2021-03-26"
steps:
  - title: Introduction
  - title: First quest
  - title: Second quest
  - title: Reflection
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
  - title: Upgrade your project
  - title: Share
  - title: What next?
