---
title: Chercheur de quête
hero_image: images/banner.png
description: Ajoute des PNJ et des quêtes au monde que tu as créé dans le projet Bâtisseur de mondes
meta_title: Apprendre Unity | Développement de jeux | Chercheur de quête
meta_description: Apprends le développement de jeux Unity avec Raspberry Pi Foundation. Ajoute des PNJ et des quêtes à un monde que tu crées en utilisant Unity.
version: 4
listed: true
copyedit: true
last_tested: '2021-03-26'
steps:
  - title: Ce que tu vas faire
  - title: Première quête
  - title: Deuxième quête
    completion:
      - engaged
      - internal
  - title: Questionnaire rapide
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - title: Améliorer ton projet
  - title: Partager
  - title: Et ensuite ?
